# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/media/nemsys/data/projects/courses/netIT/PythonCourseNetIT/PythonCourse_25.10-Labs/lab51/SimpleLoginForm/SimpleLoginForm/form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(523, 381)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 30, 521, 57))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 130, 451, 211))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.labelUsername = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelUsername.setObjectName("labelUsername")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelUsername)
        self.leUserName = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.leUserName.setObjectName("leUserName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.leUserName)
        self.labelPass = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelPass.setObjectName("labelPass")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelPass)
        self.lePass = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lePass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lePass.setObjectName("lePass")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lePass)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnSubmit = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btnSubmit.setObjectName("btnSubmit")
        self.horizontalLayout.addWidget(self.btnSubmit)
        self.btnCancel = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Simple Login Form"))
        self.labelUsername.setText(_translate("Form", "user name"))
        self.labelPass.setText(_translate("Form", "password"))
        self.btnSubmit.setText(_translate("Form", "Submit"))
        self.btnCancel.setText(_translate("Form", "Cancel"))
